dofile_once("mods/nathans_things/files/spells/delta.lua")
dofile_once("mods/nathans_things/files/spells/memory_spell.lua")
dofile_once("mods/nathans_things/files/spells/pi.lua")
dofile_once("mods/nathans_things/files/spells/pi2.lua")
dofile_once("mods/nathans_things/files/spells/theta.lua")
dofile_once("mods/nathans_things/files/spells/manifest_mana.lua")
dofile_once("mods/nathans_things/files/spells/burn_mana.lua")
dofile_once("mods/nathans_things/files/spells/mana_battery.lua")
dofile_once("mods/nathans_things/files/spells/mana_loan.lua")
dofile_once("mods/nathans_things/files/spells/bank_mana.lua")
dofile_once("mods/nathans_things/files/spells/mana_tax.lua")
dofile_once("mods/nathans_things/files/spells/invest_mana.lua")
dofile_once("mods/nathans_things/files/spells/liquify_mana.lua")




table.insert(actions,delta)
table.insert(actions,memory)
table.insert(actions,pi)
table.insert(actions,pi2)
table.insert(actions,theta)
table.insert(actions,manifest_mana)
table.insert(actions,burn_mana)
table.insert(actions,mana_battery)
table.insert(actions,mana_loan)
table.insert(actions,bank_mana)
table.insert(actions,mana_tax)
table.insert(actions,mana_investment)
table.insert(actions,mana_investment)
table.insert(actions,liquify_mana)
